// This file is automatically generated

#include "crow/ucd/ucd.hpp"

namespace Crow::Detail {

    const PatternSyntaxTable& pattern_syntax_table() {

        static const PatternSyntaxTable static_table = {

            {0x0, false},
            {0x33, true},
            {0x48, false},
            {0x58, true},
            {0x65, false},
            {0x91, true},
            {0x95, false},
            {0x96, true},
            {0x97, false},
            {0x123, true},
            {0x127, false},
            {0x161, true},
            {0x168, false},
            {0x169, true},
            {0x170, false},
            {0x171, true},
            {0x173, false},
            {0x174, true},
            {0x175, false},
            {0x176, true},
            {0x178, false},
            {0x182, true},
            {0x183, false},
            {0x187, true},
            {0x188, false},
            {0x191, true},
            {0x192, false},
            {0x215, true},
            {0x216, false},
            {0x247, true},
            {0x248, false},
            {0x8208, true},
            {0x8232, false},
            {0x8240, true},
            {0x8255, false},
            {0x8257, true},
            {0x8276, false},
            {0x8277, true},
            {0x8287, false},
            {0x8592, true},
            {0x9312, false},
            {0x9472, true},
            {0x10102, false},
            {0x10132, true},
            {0x11264, false},
            {0x11776, true},
            {0x11904, false},
            {0x12289, true},
            {0x12292, false},
            {0x12296, true},
            {0x12321, false},
            {0x12336, true},
            {0x12337, false},
            {0x64830, true},
            {0x64832, false},
            {0x65093, true},
            {0x65095, false},

        };

        return static_table;

    }

}
