// This file is automatically generated

#include "crow/ucd/ucd.hpp"

namespace Crow::Detail {

    const BooleanPropertyTable& pattern_syntax_table() {

        static const BooleanPropertyTable static_table = {

            {0x0, false},
            {0x21, true},
            {0x30, false},
            {0x3a, true},
            {0x41, false},
            {0x5b, true},
            {0x5f, false},
            {0x60, true},
            {0x61, false},
            {0x7b, true},
            {0x7f, false},
            {0xa1, true},
            {0xa8, false},
            {0xa9, true},
            {0xaa, false},
            {0xab, true},
            {0xad, false},
            {0xae, true},
            {0xaf, false},
            {0xb0, true},
            {0xb2, false},
            {0xb6, true},
            {0xb7, false},
            {0xbb, true},
            {0xbc, false},
            {0xbf, true},
            {0xc0, false},
            {0xd7, true},
            {0xd8, false},
            {0xf7, true},
            {0xf8, false},
            {0x2010, true},
            {0x2028, false},
            {0x2030, true},
            {0x203f, false},
            {0x2041, true},
            {0x2054, false},
            {0x2055, true},
            {0x205f, false},
            {0x2190, true},
            {0x2460, false},
            {0x2500, true},
            {0x2776, false},
            {0x2794, true},
            {0x2c00, false},
            {0x2e00, true},
            {0x2e80, false},
            {0x3001, true},
            {0x3004, false},
            {0x3008, true},
            {0x3021, false},
            {0x3030, true},
            {0x3031, false},
            {0xfd3e, true},
            {0xfd40, false},
            {0xfe45, true},
            {0xfe47, false},

        };

        return static_table;

    }

}
