#include "crow/xml.hpp"
#include <vector>

namespace Crow::Xml::Detail {

    // https://en.wikipedia.org/wiki/List_of_XML_and_HTML_character_entity_references

    const StringViewSet& html_self_closing_tags() {

        static const StringViewSet set = {
            "area",
            "base",
            "br",
            "col",
            "command",
            "embed",
            "hr",
            "img",
            "input",
            "keygen",
            "link",
            "menuitem",
            "meta",
            "param",
            "source",
            "track",
            "wbr",
        };

        return set;

    }

    const StringViewMap& xml_entity_table() {

        static const StringViewMap map = {
            { "amp",   "&"   },
            { "lt",    "<"   },
            { "gt",    ">"   },
            { "quot",  "\""  },
            { "apos",  "'"   },
        };

        return map;

    }

    const StringViewMap& html_entity_table() {

        static const auto map = [] {

            std::vector<std::vector<const char*>> inverse_map = {

                { "\t",            "Tab" },
                { "\n",            "NewLine" },
                { "!",             "excl" },
                { "\"",            "QUOT" },
                { "#",             "num" },
                { "$",             "dollar" },
                { "%",             "percnt" },
                { "&",             "AMP" },
                { "(",             "lpar" },
                { ")",             "rpar" },
                { "*",             "ast", "midast" },
                { "+",             "plus" },
                { ",",             "comma" },
                { ".",             "period" },
                { "/",             "sol" },
                { ":",             "colon" },
                { ";",             "semi" },
                { "<",             "LT" },
                { "=",             "equals" },
                { ">",             "GT" },
                { "?",             "quest" },
                { "@",             "commat" },
                { "[",             "lbrack", "lsqb" },
                { "\\",            "bsol" },
                { "]",             "rbrack", "rsqb" },
                { "^",             "Hat" },
                { "_",             "UnderBar", "lowbar" },
                { "`",             "DiacriticalGrave", "grave" },
                { "{",             "lbrace", "lcub" },
                { "|",             "VerticalLine", "verbar", "vert" },
                { "}",             "rbrace", "rcub" },
                { "\u00a0",        "NonBreakingSpace", "nbsp" },
                { "\u00a1",        "iexcl" },
                { "\u00a2",        "cent" },
                { "\u00a3",        "pound" },
                { "\u00a4",        "curren" },
                { "\u00a5",        "yen" },
                { "\u00a6",        "brvbar" },
                { "\u00a7",        "sect" },
                { "\u00a8",        "Dot", "DoubleDot", "die", "uml" },
                { "\u00a9",        "COPY", "copy" },
                { "\u00aa",        "ordf" },
                { "\u00ab",        "laquo" },
                { "\u00ac",        "not" },
                { "\u00ad",        "shy" },
                { "\u00ae",        "REG", "circledR", "reg" },
                { "\u00af",        "macr", "strns" },
                { "\u00b0",        "deg" },
                { "\u00b1",        "PlusMinus", "plusmn", "pm" },
                { "\u00b2",        "sup2" },
                { "\u00b3",        "sup3" },
                { "\u00b4",        "DiacriticalAcute", "acute" },
                { "\u00b5",        "micro" },
                { "\u00b6",        "para" },
                { "\u00b7",        "CenterDot", "centerdot", "middot" },
                { "\u00b8",        "Cedilla", "cedil" },
                { "\u00b9",        "sup1" },
                { "\u00ba",        "ordm" },
                { "\u00bb",        "raquo" },
                { "\u00bc",        "frac14" },
                { "\u00bd",        "frac12", "half" },
                { "\u00be",        "frac34" },
                { "\u00bf",        "iquest" },
                { "\u00c0",        "Agrave" },
                { "\u00c1",        "Aacute" },
                { "\u00c2",        "Acirc" },
                { "\u00c3",        "Atilde" },
                { "\u00c4",        "Auml" },
                { "\u00c5",        "Aring", "angst" },
                { "\u00c6",        "AElig" },
                { "\u00c7",        "Ccedil" },
                { "\u00c8",        "Egrave" },
                { "\u00c9",        "Eacute" },
                { "\u00ca",        "Ecirc" },
                { "\u00cb",        "Euml" },
                { "\u00cc",        "Igrave" },
                { "\u00cd",        "Iacute" },
                { "\u00ce",        "Icirc" },
                { "\u00cf",        "Iuml" },
                { "\u00d0",        "ETH" },
                { "\u00d1",        "Ntilde" },
                { "\u00d2",        "Ograve" },
                { "\u00d3",        "Oacute" },
                { "\u00d4",        "Ocirc" },
                { "\u00d5",        "Otilde" },
                { "\u00d6",        "Ouml" },
                { "\u00d7",        "times" },
                { "\u00d8",        "Oslash" },
                { "\u00d9",        "Ugrave" },
                { "\u00da",        "Uacute" },
                { "\u00db",        "Ucirc" },
                { "\u00dc",        "Uuml" },
                { "\u00dd",        "Yacute" },
                { "\u00de",        "THORN" },
                { "\u00df",        "szlig" },
                { "\u00e0",        "agrave" },
                { "\u00e1",        "aacute" },
                { "\u00e2",        "acirc" },
                { "\u00e3",        "atilde" },
                { "\u00e4",        "auml" },
                { "\u00e5",        "aring" },
                { "\u00e6",        "aelig" },
                { "\u00e7",        "ccedil" },
                { "\u00e8",        "egrave" },
                { "\u00e9",        "eacute" },
                { "\u00ea",        "ecirc" },
                { "\u00eb",        "euml" },
                { "\u00ec",        "igrave" },
                { "\u00ed",        "iacute" },
                { "\u00ee",        "icirc" },
                { "\u00ef",        "iuml" },
                { "\u00f0",        "eth" },
                { "\u00f1",        "ntilde" },
                { "\u00f2",        "ograve" },
                { "\u00f3",        "oacute" },
                { "\u00f4",        "ocirc" },
                { "\u00f5",        "otilde" },
                { "\u00f6",        "ouml" },
                { "\u00f7",        "div", "divide" },
                { "\u00f8",        "oslash" },
                { "\u00f9",        "ugrave" },
                { "\u00fa",        "uacute" },
                { "\u00fb",        "ucirc" },
                { "\u00fc",        "uuml" },
                { "\u00fd",        "yacute" },
                { "\u00fe",        "thorn" },
                { "\u00ff",        "yuml" },
                { "\u0100",        "Amacr" },
                { "\u0101",        "amacr" },
                { "\u0102",        "Abreve" },
                { "\u0103",        "abreve" },
                { "\u0104",        "Aogon" },
                { "\u0105",        "aogon" },
                { "\u0106",        "Cacute" },
                { "\u0107",        "cacute" },
                { "\u0108",        "Ccirc" },
                { "\u0109",        "ccirc" },
                { "\u010a",        "Cdot" },
                { "\u010b",        "cdot" },
                { "\u010c",        "Ccaron" },
                { "\u010d",        "ccaron" },
                { "\u010e",        "Dcaron" },
                { "\u010f",        "dcaron" },
                { "\u0110",        "Dstrok" },
                { "\u0111",        "dstrok" },
                { "\u0112",        "Emacr" },
                { "\u0113",        "emacr" },
                { "\u0116",        "Edot" },
                { "\u0117",        "edot" },
                { "\u0118",        "Eogon" },
                { "\u0119",        "eogon" },
                { "\u011a",        "Ecaron" },
                { "\u011b",        "ecaron" },
                { "\u011c",        "Gcirc" },
                { "\u011d",        "gcirc" },
                { "\u011e",        "Gbreve" },
                { "\u011f",        "gbreve" },
                { "\u0120",        "Gdot" },
                { "\u0121",        "gdot" },
                { "\u0122",        "Gcedil" },
                { "\u0124",        "Hcirc" },
                { "\u0125",        "hcirc" },
                { "\u0126",        "Hstrok" },
                { "\u0127",        "hstrok" },
                { "\u0128",        "Itilde" },
                { "\u0129",        "itilde" },
                { "\u012a",        "Imacr" },
                { "\u012b",        "imacr" },
                { "\u012e",        "Iogon" },
                { "\u012f",        "iogon" },
                { "\u0130",        "Idot" },
                { "\u0131",        "imath", "inodot" },
                { "\u0132",        "IJlig" },
                { "\u0133",        "ijlig" },
                { "\u0134",        "Jcirc" },
                { "\u0135",        "jcirc" },
                { "\u0136",        "Kcedil" },
                { "\u0137",        "kcedil" },
                { "\u0138",        "kgreen" },
                { "\u0139",        "Lacute" },
                { "\u013a",        "lacute" },
                { "\u013b",        "Lcedil" },
                { "\u013c",        "lcedil" },
                { "\u013d",        "Lcaron" },
                { "\u013e",        "lcaron" },
                { "\u013f",        "Lmidot" },
                { "\u0140",        "lmidot" },
                { "\u0141",        "Lstrok" },
                { "\u0142",        "lstrok" },
                { "\u0143",        "Nacute" },
                { "\u0144",        "nacute" },
                { "\u0145",        "Ncedil" },
                { "\u0146",        "ncedil" },
                { "\u0147",        "Ncaron" },
                { "\u0148",        "ncaron" },
                { "\u0149",        "napos" },
                { "\u014a",        "ENG" },
                { "\u014b",        "eng" },
                { "\u014c",        "Omacr" },
                { "\u014d",        "omacr" },
                { "\u0150",        "Odblac" },
                { "\u0151",        "odblac" },
                { "\u0152",        "OElig" },
                { "\u0153",        "oelig" },
                { "\u0154",        "Racute" },
                { "\u0155",        "racute" },
                { "\u0156",        "Rcedil" },
                { "\u0157",        "rcedil" },
                { "\u0158",        "Rcaron" },
                { "\u0159",        "rcaron" },
                { "\u015a",        "Sacute" },
                { "\u015b",        "sacute" },
                { "\u015c",        "Scirc" },
                { "\u015d",        "scirc" },
                { "\u015e",        "Scedil" },
                { "\u015f",        "scedil" },
                { "\u0160",        "Scaron" },
                { "\u0161",        "scaron" },
                { "\u0162",        "Tcedil" },
                { "\u0163",        "tcedil" },
                { "\u0164",        "Tcaron" },
                { "\u0165",        "tcaron" },
                { "\u0166",        "Tstrok" },
                { "\u0167",        "tstrok" },
                { "\u0168",        "Utilde" },
                { "\u0169",        "utilde" },
                { "\u016a",        "Umacr" },
                { "\u016b",        "umacr" },
                { "\u016c",        "Ubreve" },
                { "\u016d",        "ubreve" },
                { "\u016e",        "Uring" },
                { "\u016f",        "uring" },
                { "\u0170",        "Udblac" },
                { "\u0171",        "udblac" },
                { "\u0172",        "Uogon" },
                { "\u0173",        "uogon" },
                { "\u0174",        "Wcirc" },
                { "\u0175",        "wcirc" },
                { "\u0176",        "Ycirc" },
                { "\u0177",        "ycirc" },
                { "\u0178",        "Yuml" },
                { "\u0179",        "Zacute" },
                { "\u017a",        "zacute" },
                { "\u017b",        "Zdot" },
                { "\u017c",        "zdot" },
                { "\u017d",        "Zcaron" },
                { "\u017e",        "zcaron" },
                { "\u0192",        "fnof" },
                { "\u01b5",        "imped" },
                { "\u01f5",        "gacute" },
                { "\u0237",        "jmath" },
                { "\u02c6",        "circ" },
                { "\u02c7",        "Hacek", "caron" },
                { "\u02d8",        "Breve", "breve" },
                { "\u02d9",        "DiacriticalDot", "dot" },
                { "\u02da",        "ring" },
                { "\u02db",        "ogon" },
                { "\u02dc",        "DiacriticalTilde", "tilde" },
                { "\u02dd",        "DiacriticalDoubleAcute", "dblac" },
                { "\u0311",        "DownBreve" },
                { "\u0391",        "Alpha" },
                { "\u0392",        "Beta" },
                { "\u0393",        "Gamma" },
                { "\u0394",        "Delta" },
                { "\u0395",        "Epsilon" },
                { "\u0396",        "Zeta" },
                { "\u0397",        "Eta" },
                { "\u0398",        "Theta" },
                { "\u0399",        "Iota" },
                { "\u039a",        "Kappa" },
                { "\u039b",        "Lambda" },
                { "\u039c",        "Mu" },
                { "\u039d",        "Nu" },
                { "\u039e",        "Xi" },
                { "\u039f",        "Omicron" },
                { "\u03a0",        "Pi" },
                { "\u03a1",        "Rho" },
                { "\u03a3",        "Sigma" },
                { "\u03a4",        "Tau" },
                { "\u03a5",        "Upsilon" },
                { "\u03a6",        "Phi" },
                { "\u03a7",        "Chi" },
                { "\u03a8",        "Psi" },
                { "\u03a9",        "Omega", "ohm" },
                { "\u03b1",        "alpha" },
                { "\u03b2",        "beta" },
                { "\u03b3",        "gamma" },
                { "\u03b4",        "delta" },
                { "\u03b5",        "epsi", "epsilon" },
                { "\u03b6",        "zeta" },
                { "\u03b7",        "eta" },
                { "\u03b8",        "theta" },
                { "\u03b9",        "iota" },
                { "\u03ba",        "kappa" },
                { "\u03bb",        "lambda" },
                { "\u03bc",        "mu" },
                { "\u03bd",        "nu" },
                { "\u03be",        "xi" },
                { "\u03bf",        "omicron" },
                { "\u03c0",        "pi" },
                { "\u03c1",        "rho" },
                { "\u03c2",        "sigmaf", "sigmav", "varsigma" },
                { "\u03c3",        "sigma" },
                { "\u03c4",        "tau" },
                { "\u03c5",        "upsi", "upsilon" },
                { "\u03c6",        "phi" },
                { "\u03c7",        "chi" },
                { "\u03c8",        "psi" },
                { "\u03c9",        "omega" },
                { "\u03d1",        "thetasym", "thetav", "vartheta" },
                { "\u03d2",        "Upsi", "upsih" },
                { "\u03d5",        "phiv", "straightphi", "varphi" },
                { "\u03d6",        "piv", "varpi" },
                { "\u03dc",        "Gammad" },
                { "\u03dd",        "digamma", "gammad" },
                { "\u03f0",        "kappav", "varkappa" },
                { "\u03f1",        "rhov", "varrho" },
                { "\u03f5",        "epsiv", "straightepsilon", "varepsilon" },
                { "\u03f6",        "backepsilon", "bepsi" },
                { "\u0401",        "IOcy" },
                { "\u0402",        "DJcy" },
                { "\u0403",        "GJcy" },
                { "\u0404",        "Jukcy" },
                { "\u0405",        "DScy" },
                { "\u0406",        "Iukcy" },
                { "\u0407",        "YIcy" },
                { "\u0408",        "Jsercy" },
                { "\u0409",        "LJcy" },
                { "\u040a",        "NJcy" },
                { "\u040b",        "TSHcy" },
                { "\u040c",        "KJcy" },
                { "\u040e",        "Ubrcy" },
                { "\u040f",        "DZcy" },
                { "\u0410",        "Acy" },
                { "\u0411",        "Bcy" },
                { "\u0412",        "Vcy" },
                { "\u0413",        "Gcy" },
                { "\u0414",        "Dcy" },
                { "\u0415",        "IEcy" },
                { "\u0416",        "ZHcy" },
                { "\u0417",        "Zcy" },
                { "\u0418",        "Icy" },
                { "\u0419",        "Jcy" },
                { "\u041a",        "Kcy" },
                { "\u041b",        "Lcy" },
                { "\u041c",        "Mcy" },
                { "\u041d",        "Ncy" },
                { "\u041e",        "Ocy" },
                { "\u041f",        "Pcy" },
                { "\u0420",        "Rcy" },
                { "\u0421",        "Scy" },
                { "\u0422",        "Tcy" },
                { "\u0423",        "Ucy" },
                { "\u0424",        "Fcy" },
                { "\u0425",        "KHcy" },
                { "\u0426",        "TScy" },
                { "\u0427",        "CHcy" },
                { "\u0428",        "SHcy" },
                { "\u0429",        "SHCHcy" },
                { "\u042a",        "HARDcy" },
                { "\u042b",        "Ycy" },
                { "\u042c",        "SOFTcy" },
                { "\u042d",        "Ecy" },
                { "\u042e",        "YUcy" },
                { "\u042f",        "YAcy" },
                { "\u0430",        "acy" },
                { "\u0431",        "bcy" },
                { "\u0432",        "vcy" },
                { "\u0433",        "gcy" },
                { "\u0434",        "dcy" },
                { "\u0435",        "iecy" },
                { "\u0436",        "zhcy" },
                { "\u0437",        "zcy" },
                { "\u0438",        "icy" },
                { "\u0439",        "jcy" },
                { "\u043a",        "kcy" },
                { "\u043b",        "lcy" },
                { "\u043c",        "mcy" },
                { "\u043d",        "ncy" },
                { "\u043e",        "ocy" },
                { "\u043f",        "pcy" },
                { "\u0440",        "rcy" },
                { "\u0441",        "scy" },
                { "\u0442",        "tcy" },
                { "\u0443",        "ucy" },
                { "\u0444",        "fcy" },
                { "\u0445",        "khcy" },
                { "\u0446",        "tscy" },
                { "\u0447",        "chcy" },
                { "\u0448",        "shcy" },
                { "\u0449",        "shchcy" },
                { "\u044a",        "hardcy" },
                { "\u044b",        "ycy" },
                { "\u044c",        "softcy" },
                { "\u044d",        "ecy" },
                { "\u044e",        "yucy" },
                { "\u044f",        "yacy" },
                { "\u0451",        "iocy" },
                { "\u0452",        "djcy" },
                { "\u0453",        "gjcy" },
                { "\u0454",        "jukcy" },
                { "\u0455",        "dscy" },
                { "\u0456",        "iukcy" },
                { "\u0457",        "yicy" },
                { "\u0458",        "jsercy" },
                { "\u0459",        "ljcy" },
                { "\u045a",        "njcy" },
                { "\u045b",        "tshcy" },
                { "\u045c",        "kjcy" },
                { "\u045e",        "ubrcy" },
                { "\u045f",        "dzcy" },
                { "\u2002",        "ensp" },
                { "\u2003",        "emsp" },
                { "\u2004",        "emsp13" },
                { "\u2005",        "emsp14" },
                { "\u2007",        "numsp" },
                { "\u2008",        "puncsp" },
                { "\u2009",        "ThinSpace", "thinsp" },
                { "\u200a",        "VeryThinSpace", "hairsp" },
                { "\u200b",        "NegativeMediumSpace", "NegativeThickSpace", "NegativeThinSpace", "NegativeVeryThinSpace", "ZeroWidthSpace" },
                { "\u200c",        "zwnj" },
                { "\u200d",        "zwj" },
                { "\u200e",        "lrm" },
                { "\u200f",        "rlm" },
                { "\u2010",        "dash", "hyphen" },
                { "\u2013",        "ndash" },
                { "\u2014",        "mdash" },
                { "\u2015",        "horbar" },
                { "\u2016",        "Verbar", "Vert" },
                { "\u2018",        "OpenCurlyQuote", "lsquo" },
                { "\u2019",        "CloseCurlyQuote", "rsquo", "rsquor" },
                { "\u201a",        "lsquor", "sbquo" },
                { "\u201c",        "OpenCurlyDoubleQuote", "ldquo" },
                { "\u201d",        "CloseCurlyDoubleQuote", "rdquo", "rdquor" },
                { "\u201e",        "bdquo", "ldquor" },
                { "\u2020",        "dagger" },
                { "\u2021",        "Dagger", "ddagger" },
                { "\u2022",        "bull", "bullet" },
                { "\u2025",        "nldr" },
                { "\u2026",        "hellip", "mldr" },
                { "\u2030",        "permil" },
                { "\u2031",        "pertenk" },
                { "\u2032",        "prime" },
                { "\u2033",        "Prime" },
                { "\u2034",        "tprime" },
                { "\u2035",        "backprime", "bprime" },
                { "\u2039",        "lsaquo" },
                { "\u203a",        "rsaquo" },
                { "\u203e",        "OverBar", "oline" },
                { "\u2041",        "caret" },
                { "\u2043",        "hybull" },
                { "\u2044",        "frasl" },
                { "\u204f",        "bsemi" },
                { "\u2057",        "qprime" },
                { "\u205f",        "MediumSpace" },
                { "\u2060",        "NoBreak" },
                { "\u2061",        "ApplyFunction", "af" },
                { "\u2062",        "InvisibleTimes", "it" },
                { "\u2063",        "InvisibleComma", "ic" },
                { "\u20ac",        "euro" },
                { "\u20db",        "TripleDot", "tdot" },
                { "\u20dc",        "DotDot" },
                { "\u2102",        "Copf", "complexes" },
                { "\u2105",        "incare" },
                { "\u210a",        "gscr" },
                { "\u210b",        "HilbertSpace", "Hscr", "hamilt" },
                { "\u210c",        "Hfr", "Poincareplane" },
                { "\u210d",        "Hopf", "quaternions" },
                { "\u210e",        "planckh" },
                { "\u210f",        "hbar", "hslash", "planck", "plankv" },
                { "\u2110",        "Iscr", "imagline" },
                { "\u2111",        "Ifr", "Im", "image", "imagpart" },
                { "\u2112",        "Laplacetrf", "Lscr", "lagran" },
                { "\u2113",        "ell" },
                { "\u2115",        "Nopf", "naturals" },
                { "\u2116",        "numero" },
                { "\u2117",        "copysr" },
                { "\u2118",        "weierp", "wp" },
                { "\u2119",        "Popf", "primes" },
                { "\u211a",        "Qopf", "rationals" },
                { "\u211b",        "Rscr", "realine" },
                { "\u211c",        "Re", "Rfr", "real", "realpart" },
                { "\u211d",        "Ropf", "reals" },
                { "\u211e",        "rx" },
                { "\u2122",        "TRADE", "trade" },
                { "\u2124",        "Zopf", "integers" },
                { "\u2127",        "mho" },
                { "\u2128",        "Zfr", "zeetrf" },
                { "\u2129",        "iiota" },
                { "\u212c",        "Bernoullis", "Bscr", "bernou" },
                { "\u212d",        "Cayleys", "Cfr" },
                { "\u212f",        "escr" },
                { "\u2130",        "Escr", "expectation" },
                { "\u2131",        "Fouriertrf", "Fscr" },
                { "\u2133",        "Mellintrf", "Mscr", "phmmat" },
                { "\u2134",        "order", "orderof", "oscr" },
                { "\u2135",        "alefsym", "aleph" },
                { "\u2136",        "beth" },
                { "\u2137",        "gimel" },
                { "\u2138",        "daleth" },
                { "\u2145",        "CapitalDifferentialD", "DD" },
                { "\u2146",        "DifferentialD", "dd" },
                { "\u2147",        "ExponentialE", "ee", "exponentiale" },
                { "\u2148",        "ImaginaryI", "ii" },
                { "\u2153",        "frac13" },
                { "\u2154",        "frac23" },
                { "\u2155",        "frac15" },
                { "\u2156",        "frac25" },
                { "\u2157",        "frac35" },
                { "\u2158",        "frac45" },
                { "\u2159",        "frac16" },
                { "\u215a",        "frac56" },
                { "\u215b",        "frac18" },
                { "\u215c",        "frac38" },
                { "\u215d",        "frac58" },
                { "\u215e",        "frac78" },
                { "\u2190",        "LeftArrow", "ShortLeftArrow", "larr", "leftarrow", "slarr" },
                { "\u2191",        "ShortUpArrow", "UpArrow", "uarr", "uparrow" },
                { "\u2192",        "RightArrow", "ShortRightArrow", "rarr", "rightarrow", "srarr" },
                { "\u2193",        "DownArrow", "ShortDownArrow", "darr", "downarrow" },
                { "\u2194",        "LeftRightArrow", "harr", "leftrightarrow" },
                { "\u2195",        "UpDownArrow", "updownarrow", "varr" },
                { "\u2196",        "UpperLeftArrow", "nwarr", "nwarrow" },
                { "\u2197",        "UpperRightArrow", "nearr", "nearrow" },
                { "\u2198",        "LowerRightArrow", "searr", "searrow" },
                { "\u2199",        "LowerLeftArrow", "swarr", "swarrow" },
                { "\u219a",        "nlarr", "nleftarrow" },
                { "\u219b",        "nrarr", "nrightarrow" },
                { "\u219d",        "rarrw", "rightsquigarrow" },
                { "\u219e",        "Larr", "twoheadleftarrow" },
                { "\u219f",        "Uarr" },
                { "\u21a0",        "Rarr", "twoheadrightarrow" },
                { "\u21a1",        "Darr" },
                { "\u21a2",        "larrtl", "leftarrowtail" },
                { "\u21a3",        "rarrtl", "rightarrowtail" },
                { "\u21a4",        "LeftTeeArrow", "mapstoleft" },
                { "\u21a5",        "UpTeeArrow", "mapstoup" },
                { "\u21a6",        "RightTeeArrow", "map", "mapsto" },
                { "\u21a7",        "DownTeeArrow", "mapstodown" },
                { "\u21a9",        "hookleftarrow", "larrhk" },
                { "\u21aa",        "hookrightarrow", "rarrhk" },
                { "\u21ab",        "larrlp", "looparrowleft" },
                { "\u21ac",        "looparrowright", "rarrlp" },
                { "\u21ad",        "harrw", "leftrightsquigarrow" },
                { "\u21ae",        "nharr", "nleftrightarrow" },
                { "\u21b0",        "Lsh", "lsh" },
                { "\u21b1",        "Rsh", "rsh" },
                { "\u21b2",        "ldsh" },
                { "\u21b3",        "rdsh" },
                { "\u21b5",        "crarr" },
                { "\u21b6",        "cularr", "curvearrowleft" },
                { "\u21b7",        "curarr", "curvearrowright" },
                { "\u21ba",        "circlearrowleft", "olarr" },
                { "\u21bb",        "circlearrowright", "orarr" },
                { "\u21bc",        "LeftVector", "leftharpoonup", "lharu" },
                { "\u21bd",        "DownLeftVector", "leftharpoondown", "lhard" },
                { "\u21be",        "RightUpVector", "uharr", "upharpoonright" },
                { "\u21bf",        "LeftUpVector", "uharl", "upharpoonleft" },
                { "\u21c0",        "RightVector", "rharu", "rightharpoonup" },
                { "\u21c1",        "DownRightVector", "rhard", "rightharpoondown" },
                { "\u21c2",        "RightDownVector", "dharr", "downharpoonright" },
                { "\u21c3",        "LeftDownVector", "dharl", "downharpoonleft" },
                { "\u21c4",        "RightArrowLeftArrow", "rightleftarrows", "rlarr" },
                { "\u21c5",        "UpArrowDownArrow", "udarr" },
                { "\u21c6",        "LeftArrowRightArrow", "leftrightarrows", "lrarr" },
                { "\u21c7",        "leftleftarrows", "llarr" },
                { "\u21c8",        "upuparrows", "uuarr" },
                { "\u21c9",        "rightrightarrows", "rrarr" },
                { "\u21ca",        "ddarr", "downdownarrows" },
                { "\u21cb",        "ReverseEquilibrium", "leftrightharpoons", "lrhar" },
                { "\u21cc",        "Equilibrium", "rightleftharpoons", "rlhar" },
                { "\u21cd",        "nLeftarrow", "nlArr" },
                { "\u21ce",        "nLeftrightarrow", "nhArr" },
                { "\u21cf",        "nRightarrow", "nrArr" },
                { "\u21d0",        "DoubleLeftArrow", "Leftarrow", "lArr" },
                { "\u21d1",        "DoubleUpArrow", "Uparrow", "uArr" },
                { "\u21d2",        "DoubleRightArrow", "Implies", "Rightarrow", "rArr" },
                { "\u21d3",        "DoubleDownArrow", "Downarrow", "dArr" },
                { "\u21d4",        "DoubleLeftRightArrow", "Leftrightarrow", "hArr", "iff" },
                { "\u21d5",        "DoubleUpDownArrow", "Updownarrow", "vArr" },
                { "\u21d6",        "nwArr" },
                { "\u21d7",        "neArr" },
                { "\u21d8",        "seArr" },
                { "\u21d9",        "swArr" },
                { "\u21da",        "Lleftarrow", "lAarr" },
                { "\u21db",        "Rrightarrow", "rAarr" },
                { "\u21dd",        "zigrarr" },
                { "\u21e4",        "LeftArrowBar", "larrb" },
                { "\u21e5",        "RightArrowBar", "rarrb" },
                { "\u21f5",        "DownArrowUpArrow", "duarr" },
                { "\u21fd",        "loarr" },
                { "\u21fe",        "roarr" },
                { "\u21ff",        "hoarr" },
                { "\u2200",        "ForAll", "forall" },
                { "\u2201",        "comp", "complement" },
                { "\u2202",        "PartialD", "part" },
                { "\u2203",        "Exists", "exist" },
                { "\u2204",        "NotExists", "nexist", "nexists" },
                { "\u2205",        "empty", "emptyset", "emptyv", "varnothing" },
                { "\u2207",        "Del", "nabla" },
                { "\u2208",        "Element", "in", "isin", "isinv" },
                { "\u2209",        "NotElement", "notin", "notinva" },
                { "\u220b",        "ReverseElement", "SuchThat", "ni", "niv" },
                { "\u220c",        "NotReverseElement", "notni", "notniva" },
                { "\u220f",        "Product", "prod" },
                { "\u2210",        "Coproduct", "coprod" },
                { "\u2211",        "Sum", "sum" },
                { "\u2212",        "minus" },
                { "\u2213",        "MinusPlus", "mnplus", "mp" },
                { "\u2214",        "dotplus", "plusdo" },
                { "\u2216",        "Backslash", "setminus", "setmn", "smallsetminus", "ssetmn" },
                { "\u2217",        "lowast" },
                { "\u2218",        "SmallCircle", "compfn" },
                { "\u221a",        "Sqrt", "radic" },
                { "\u221d",        "Proportional", "prop", "propto", "varpropto", "vprop" },
                { "\u221e",        "infin" },
                { "\u221f",        "angrt" },
                { "\u2220",        "ang", "angle" },
                { "\u2221",        "angmsd", "measuredangle" },
                { "\u2222",        "angsph" },
                { "\u2223",        "VerticalBar", "mid", "shortmid", "smid" },
                { "\u2224",        "NotVerticalBar", "nmid", "nshortmid", "nsmid" },
                { "\u2225",        "DoubleVerticalBar", "par", "parallel", "shortparallel", "spar" },
                { "\u2226",        "NotDoubleVerticalBar", "npar", "nparallel", "nshortparallel", "nspar" },
                { "\u2227",        "and", "wedge" },
                { "\u2228",        "or", "vee" },
                { "\u2229",        "cap" },
                { "\u222a",        "cup" },
                { "\u222b",        "Integral", "int" },
                { "\u222c",        "Int" },
                { "\u222d",        "iiint", "tint" },
                { "\u222e",        "ContourIntegral", "conint", "oint" },
                { "\u222f",        "Conint", "DoubleContourIntegral" },
                { "\u2230",        "Cconint" },
                { "\u2231",        "cwint" },
                { "\u2232",        "ClockwiseContourIntegral", "cwconint" },
                { "\u2233",        "CounterClockwiseContourIntegral", "awconint" },
                { "\u2234",        "Therefore", "there4", "therefore" },
                { "\u2235",        "Because", "becaus", "because" },
                { "\u2236",        "ratio" },
                { "\u2237",        "Colon", "Proportion" },
                { "\u2238",        "dotminus", "minusd" },
                { "\u223a",        "mDDot" },
                { "\u223b",        "homtht" },
                { "\u223c",        "Tilde", "sim", "thicksim", "thksim" },
                { "\u223d",        "backsim", "bsim" },
                { "\u223e",        "ac", "mstpos" },
                { "\u223f",        "acd" },
                { "\u2240",        "VerticalTilde", "wr", "wreath" },
                { "\u2241",        "NotTilde", "nsim" },
                { "\u2242",        "EqualTilde", "eqsim", "esim" },
                { "\u2243",        "TildeEqual", "sime", "simeq" },
                { "\u2244",        "NotTildeEqual", "nsime", "nsimeq" },
                { "\u2245",        "TildeFullEqual", "cong" },
                { "\u2246",        "simne" },
                { "\u2247",        "NotTildeFullEqual", "ncong" },
                { "\u2248",        "TildeTilde", "ap", "approx", "asymp", "thickapprox", "thkap" },
                { "\u2249",        "NotTildeTilde", "nap", "napprox" },
                { "\u224a",        "ape", "approxeq" },
                { "\u224b",        "apid" },
                { "\u224c",        "backcong", "bcong" },
                { "\u224d",        "CupCap", "asympeq" },
                { "\u224e",        "Bumpeq", "HumpDownHump", "bump" },
                { "\u224f",        "HumpEqual", "bumpe", "bumpeq" },
                { "\u2250",        "DotEqual", "doteq", "esdot" },
                { "\u2251",        "doteqdot", "eDot" },
                { "\u2252",        "efDot", "fallingdotseq" },
                { "\u2253",        "erDot", "risingdotseq" },
                { "\u2254",        "Assign", "colone", "coloneq" },
                { "\u2255",        "ecolon", "eqcolon" },
                { "\u2256",        "ecir", "eqcirc" },
                { "\u2257",        "circeq", "cire" },
                { "\u2259",        "wedgeq" },
                { "\u225a",        "veeeq" },
                { "\u225c",        "triangleq", "trie" },
                { "\u225f",        "equest", "questeq" },
                { "\u2260",        "NotEqual", "ne" },
                { "\u2261",        "Congruent", "equiv" },
                { "\u2262",        "NotCongruent", "nequiv" },
                { "\u2264",        "le", "leq" },
                { "\u2265",        "GreaterEqual", "ge", "geq" },
                { "\u2266",        "LessFullEqual", "lE", "leqq" },
                { "\u2267",        "GreaterFullEqual", "gE", "geqq" },
                { "\u2268",        "lnE", "lneqq" },
                { "\u2269",        "gnE", "gneqq" },
                { "\u226a",        "Lt", "NestedLessLess", "ll" },
                { "\u226b",        "Gt", "NestedGreaterGreater", "gg" },
                { "\u226c",        "between", "twixt" },
                { "\u226d",        "NotCupCap" },
                { "\u226e",        "NotLess", "nless", "nlt" },
                { "\u226f",        "NotGreater", "ngt", "ngtr" },
                { "\u2270",        "NotLessEqual", "nle", "nleq" },
                { "\u2271",        "NotGreaterEqual", "nge", "ngeq" },
                { "\u2272",        "LessTilde", "lesssim", "lsim" },
                { "\u2273",        "GreaterTilde", "gsim", "gtrsim" },
                { "\u2274",        "NotLessTilde", "nlsim" },
                { "\u2275",        "NotGreaterTilde", "ngsim" },
                { "\u2276",        "LessGreater", "lessgtr", "lg" },
                { "\u2277",        "GreaterLess", "gl", "gtrless" },
                { "\u2278",        "NotLessGreater", "ntlg" },
                { "\u2279",        "NotGreaterLess", "ntgl" },
                { "\u227a",        "Precedes", "pr", "prec" },
                { "\u227b",        "Succeeds", "sc", "succ" },
                { "\u227c",        "PrecedesSlantEqual", "prcue", "preccurlyeq" },
                { "\u227d",        "SucceedsSlantEqual", "sccue", "succcurlyeq" },
                { "\u227e",        "PrecedesTilde", "precsim", "prsim" },
                { "\u227f",        "SucceedsTilde", "scsim", "succsim" },
                { "\u2280",        "NotPrecedes", "npr", "nprec" },
                { "\u2281",        "NotSucceeds", "nsc", "nsucc" },
                { "\u2282",        "sub", "subset" },
                { "\u2283",        "Superset", "sup", "supset" },
                { "\u2284",        "nsub" },
                { "\u2285",        "nsup" },
                { "\u2286",        "SubsetEqual", "sube", "subseteq" },
                { "\u2287",        "SupersetEqual", "supe", "supseteq" },
                { "\u2288",        "NotSubsetEqual", "nsube", "nsubseteq" },
                { "\u2289",        "NotSupersetEqual", "nsupe", "nsupseteq" },
                { "\u228a",        "subne", "subsetneq" },
                { "\u228b",        "supne", "supsetneq" },
                { "\u228d",        "cupdot" },
                { "\u228e",        "UnionPlus", "uplus" },
                { "\u228f",        "SquareSubset", "sqsub", "sqsubset" },
                { "\u2290",        "SquareSuperset", "sqsup", "sqsupset" },
                { "\u2291",        "SquareSubsetEqual", "sqsube", "sqsubseteq" },
                { "\u2292",        "SquareSupersetEqual", "sqsupe", "sqsupseteq" },
                { "\u2293",        "SquareIntersection", "sqcap" },
                { "\u2294",        "SquareUnion", "sqcup" },
                { "\u2295",        "CirclePlus", "oplus" },
                { "\u2296",        "CircleMinus", "ominus" },
                { "\u2297",        "CircleTimes", "otimes" },
                { "\u2298",        "osol" },
                { "\u2299",        "CircleDot", "odot" },
                { "\u229a",        "circledcirc", "ocir" },
                { "\u229b",        "circledast", "oast" },
                { "\u229d",        "circleddash", "odash" },
                { "\u229e",        "boxplus", "plusb" },
                { "\u229f",        "boxminus", "minusb" },
                { "\u22a0",        "boxtimes", "timesb" },
                { "\u22a1",        "dotsquare", "sdotb" },
                { "\u22a2",        "RightTee", "vdash" },
                { "\u22a3",        "LeftTee", "dashv" },
                { "\u22a4",        "DownTee", "top" },
                { "\u22a5",        "UpTee", "bot", "bottom", "perp" },
                { "\u22a7",        "models" },
                { "\u22a8",        "DoubleRightTee", "vDash" },
                { "\u22a9",        "Vdash" },
                { "\u22aa",        "Vvdash" },
                { "\u22ab",        "VDash" },
                { "\u22ac",        "nvdash" },
                { "\u22ad",        "nvDash" },
                { "\u22ae",        "nVdash" },
                { "\u22af",        "nVDash" },
                { "\u22b0",        "prurel" },
                { "\u22b2",        "LeftTriangle", "vartriangleleft", "vltri" },
                { "\u22b3",        "RightTriangle", "vartriangleright", "vrtri" },
                { "\u22b4",        "LeftTriangleEqual", "ltrie", "trianglelefteq" },
                { "\u22b5",        "RightTriangleEqual", "rtrie", "trianglerighteq" },
                { "\u22b6",        "origof" },
                { "\u22b7",        "imof" },
                { "\u22b8",        "multimap", "mumap" },
                { "\u22b9",        "hercon" },
                { "\u22ba",        "intcal", "intercal" },
                { "\u22bb",        "veebar" },
                { "\u22bd",        "barvee" },
                { "\u22be",        "angrtvb" },
                { "\u22bf",        "lrtri" },
                { "\u22c0",        "Wedge", "bigwedge", "xwedge" },
                { "\u22c1",        "Vee", "bigvee", "xvee" },
                { "\u22c2",        "Intersection", "bigcap", "xcap" },
                { "\u22c3",        "Union", "bigcup", "xcup" },
                { "\u22c4",        "Diamond", "diam", "diamond" },
                { "\u22c5",        "sdot" },
                { "\u22c6",        "Star", "sstarf" },
                { "\u22c7",        "divideontimes", "divonx" },
                { "\u22c8",        "bowtie" },
                { "\u22c9",        "ltimes" },
                { "\u22ca",        "rtimes" },
                { "\u22cb",        "leftthreetimes", "lthree" },
                { "\u22cc",        "rightthreetimes", "rthree" },
                { "\u22cd",        "backsimeq", "bsime" },
                { "\u22ce",        "curlyvee", "cuvee" },
                { "\u22cf",        "curlywedge", "cuwed" },
                { "\u22d0",        "Sub", "Subset" },
                { "\u22d1",        "Sup", "Supset" },
                { "\u22d2",        "Cap" },
                { "\u22d3",        "Cup" },
                { "\u22d4",        "fork", "pitchfork" },
                { "\u22d5",        "epar" },
                { "\u22d6",        "lessdot", "ltdot" },
                { "\u22d7",        "gtdot", "gtrdot" },
                { "\u22d8",        "Ll" },
                { "\u22d9",        "Gg", "ggg" },
                { "\u22da",        "LessEqualGreater", "leg", "lesseqgtr" },
                { "\u22db",        "GreaterEqualLess", "gel", "gtreqless" },
                { "\u22de",        "cuepr", "curlyeqprec" },
                { "\u22df",        "cuesc", "curlyeqsucc" },
                { "\u22e0",        "NotPrecedesSlantEqual", "nprcue" },
                { "\u22e1",        "NotSucceedsSlantEqual", "nsccue" },
                { "\u22e2",        "NotSquareSubsetEqual", "nsqsube" },
                { "\u22e3",        "NotSquareSupersetEqual", "nsqsupe" },
                { "\u22e6",        "lnsim" },
                { "\u22e7",        "gnsim" },
                { "\u22e8",        "precnsim", "prnsim" },
                { "\u22e9",        "scnsim", "succnsim" },
                { "\u22ea",        "NotLeftTriangle", "nltri", "ntriangleleft" },
                { "\u22eb",        "NotRightTriangle", "nrtri", "ntriangleright" },
                { "\u22ec",        "NotLeftTriangleEqual", "nltrie", "ntrianglelefteq" },
                { "\u22ed",        "NotRightTriangleEqual", "nrtrie", "ntrianglerighteq" },
                { "\u22ee",        "vellip" },
                { "\u22ef",        "ctdot" },
                { "\u22f0",        "utdot" },
                { "\u22f1",        "dtdot" },
                { "\u22f2",        "disin" },
                { "\u22f3",        "isinsv" },
                { "\u22f4",        "isins" },
                { "\u22f5",        "isindot" },
                { "\u22f6",        "notinvc" },
                { "\u22f7",        "notinvb" },
                { "\u22f9",        "isinE" },
                { "\u22fa",        "nisd" },
                { "\u22fb",        "xnis" },
                { "\u22fc",        "nis" },
                { "\u22fd",        "notnivc" },
                { "\u22fe",        "notnivb" },
                { "\u2305",        "barwed", "barwedge" },
                { "\u2306",        "Barwed", "doublebarwedge" },
                { "\u2308",        "LeftCeiling", "lceil" },
                { "\u2309",        "RightCeiling", "rceil" },
                { "\u230a",        "LeftFloor", "lfloor" },
                { "\u230b",        "RightFloor", "rfloor" },
                { "\u230c",        "drcrop" },
                { "\u230d",        "dlcrop" },
                { "\u230e",        "urcrop" },
                { "\u230f",        "ulcrop" },
                { "\u2310",        "bnot" },
                { "\u2312",        "profline" },
                { "\u2313",        "profsurf" },
                { "\u2315",        "telrec" },
                { "\u2316",        "target" },
                { "\u231c",        "ulcorn", "ulcorner" },
                { "\u231d",        "urcorn", "urcorner" },
                { "\u231e",        "dlcorn", "llcorner" },
                { "\u231f",        "drcorn", "lrcorner" },
                { "\u2322",        "frown", "sfrown" },
                { "\u2323",        "smile", "ssmile" },
                { "\u232d",        "cylcty" },
                { "\u232e",        "profalar" },
                { "\u2336",        "topbot" },
                { "\u233d",        "ovbar" },
                { "\u233f",        "solbar" },
                { "\u237c",        "angzarr" },
                { "\u23b0",        "lmoust", "lmoustache" },
                { "\u23b1",        "rmoust", "rmoustache" },
                { "\u23b4",        "OverBracket", "tbrk" },
                { "\u23b5",        "UnderBracket", "bbrk" },
                { "\u23b6",        "bbrktbrk" },
                { "\u23dc",        "OverParenthesis" },
                { "\u23dd",        "UnderParenthesis" },
                { "\u23de",        "OverBrace" },
                { "\u23df",        "UnderBrace" },
                { "\u23e2",        "trpezium" },
                { "\u23e7",        "elinters" },
                { "\u2423",        "blank" },
                { "\u24c8",        "circledS", "oS" },
                { "\u2500",        "HorizontalLine", "boxh" },
                { "\u2502",        "boxv" },
                { "\u250c",        "boxdr" },
                { "\u2510",        "boxdl" },
                { "\u2514",        "boxur" },
                { "\u2518",        "boxul" },
                { "\u251c",        "boxvr" },
                { "\u2524",        "boxvl" },
                { "\u252c",        "boxhd" },
                { "\u2534",        "boxhu" },
                { "\u253c",        "boxvh" },
                { "\u2550",        "boxH" },
                { "\u2551",        "boxV" },
                { "\u2552",        "boxdR" },
                { "\u2553",        "boxDr" },
                { "\u2554",        "boxDR" },
                { "\u2555",        "boxdL" },
                { "\u2556",        "boxDl" },
                { "\u2557",        "boxDL" },
                { "\u2558",        "boxuR" },
                { "\u2559",        "boxUr" },
                { "\u255a",        "boxUR" },
                { "\u255b",        "boxuL" },
                { "\u255c",        "boxUl" },
                { "\u255d",        "boxUL" },
                { "\u255e",        "boxvR" },
                { "\u255f",        "boxVr" },
                { "\u2560",        "boxVR" },
                { "\u2561",        "boxvL" },
                { "\u2562",        "boxVl" },
                { "\u2563",        "boxVL" },
                { "\u2564",        "boxHd" },
                { "\u2565",        "boxhD" },
                { "\u2566",        "boxHD" },
                { "\u2567",        "boxHu" },
                { "\u2568",        "boxhU" },
                { "\u2569",        "boxHU" },
                { "\u256a",        "boxvH" },
                { "\u256b",        "boxVh" },
                { "\u256c",        "boxVH" },
                { "\u2580",        "uhblk" },
                { "\u2584",        "lhblk" },
                { "\u2588",        "block" },
                { "\u2591",        "blk14" },
                { "\u2592",        "blk12" },
                { "\u2593",        "blk34" },
                { "\u25a1",        "Square", "squ", "square" },
                { "\u25aa",        "FilledVerySmallSquare", "blacksquare", "squarf", "squf" },
                { "\u25ab",        "EmptyVerySmallSquare" },
                { "\u25ad",        "rect" },
                { "\u25ae",        "marker" },
                { "\u25b1",        "fltns" },
                { "\u25b3",        "bigtriangleup", "xutri" },
                { "\u25b4",        "blacktriangle", "utrif" },
                { "\u25b5",        "triangle", "utri" },
                { "\u25b8",        "blacktriangleright", "rtrif" },
                { "\u25b9",        "rtri", "triangleright" },
                { "\u25bd",        "bigtriangledown", "xdtri" },
                { "\u25be",        "blacktriangledown", "dtrif" },
                { "\u25bf",        "dtri", "triangledown" },
                { "\u25c2",        "blacktriangleleft", "ltrif" },
                { "\u25c3",        "ltri", "triangleleft" },
                { "\u25ca",        "loz", "lozenge" },
                { "\u25cb",        "cir" },
                { "\u25ec",        "tridot" },
                { "\u25ef",        "bigcirc", "xcirc" },
                { "\u25f8",        "ultri" },
                { "\u25f9",        "urtri" },
                { "\u25fa",        "lltri" },
                { "\u25fb",        "EmptySmallSquare" },
                { "\u25fc",        "FilledSmallSquare" },
                { "\u2605",        "bigstar", "starf" },
                { "\u2606",        "star" },
                { "\u260e",        "phone" },
                { "\u2640",        "female" },
                { "\u2642",        "male" },
                { "\u2660",        "spades", "spadesuit" },
                { "\u2663",        "clubs", "clubsuit" },
                { "\u2665",        "hearts", "heartsuit" },
                { "\u2666",        "diamondsuit", "diams" },
                { "\u266a",        "sung" },
                { "\u266d",        "flat" },
                { "\u266e",        "natur", "natural" },
                { "\u266f",        "sharp" },
                { "\u2713",        "check", "checkmark" },
                { "\u2717",        "cross" },
                { "\u2720",        "malt", "maltese" },
                { "\u2736",        "sext" },
                { "\u2758",        "VerticalSeparator" },
                { "\u2772",        "lbbrk" },
                { "\u2773",        "rbbrk" },
                { "\u27c8",        "bsolhsub" },
                { "\u27c9",        "suphsol" },
                { "\u27e6",        "LeftDoubleBracket", "lobrk" },
                { "\u27e7",        "RightDoubleBracket", "robrk" },
                { "\u27ea",        "Lang" },
                { "\u27eb",        "Rang" },
                { "\u27ec",        "loang" },
                { "\u27ed",        "roang" },
                { "\u27f5",        "LongLeftArrow", "longleftarrow", "xlarr" },
                { "\u27f6",        "LongRightArrow", "longrightarrow", "xrarr" },
                { "\u27f7",        "LongLeftRightArrow", "longleftrightarrow", "xharr" },
                { "\u27f8",        "DoubleLongLeftArrow", "Longleftarrow", "xlArr" },
                { "\u27f9",        "DoubleLongRightArrow", "Longrightarrow", "xrArr" },
                { "\u27fa",        "DoubleLongLeftRightArrow", "Longleftrightarrow", "xhArr" },
                { "\u27fc",        "longmapsto", "xmap" },
                { "\u27ff",        "dzigrarr" },
                { "\u2902",        "nvlArr" },
                { "\u2903",        "nvrArr" },
                { "\u2904",        "nvHarr" },
                { "\u2905",        "Map" },
                { "\u290c",        "lbarr" },
                { "\u290d",        "bkarow", "rbarr" },
                { "\u290e",        "lBarr" },
                { "\u290f",        "dbkarow", "rBarr" },
                { "\u2910",        "RBarr", "drbkarow" },
                { "\u2911",        "DDotrahd" },
                { "\u2912",        "UpArrowBar" },
                { "\u2913",        "DownArrowBar" },
                { "\u2916",        "Rarrtl" },
                { "\u2919",        "latail" },
                { "\u291a",        "ratail" },
                { "\u291b",        "lAtail" },
                { "\u291c",        "rAtail" },
                { "\u291d",        "larrfs" },
                { "\u291e",        "rarrfs" },
                { "\u291f",        "larrbfs" },
                { "\u2920",        "rarrbfs" },
                { "\u2923",        "nwarhk" },
                { "\u2924",        "nearhk" },
                { "\u2925",        "hksearow", "searhk" },
                { "\u2926",        "hkswarow", "swarhk" },
                { "\u2927",        "nwnear" },
                { "\u2928",        "nesear", "toea" },
                { "\u2929",        "seswar", "tosa" },
                { "\u292a",        "swnwar" },
                { "\u2933",        "rarrc" },
                { "\u2935",        "cudarrr" },
                { "\u2936",        "ldca" },
                { "\u2937",        "rdca" },
                { "\u2938",        "cudarrl" },
                { "\u2939",        "larrpl" },
                { "\u293c",        "curarrm" },
                { "\u293d",        "cularrp" },
                { "\u2945",        "rarrpl" },
                { "\u2948",        "harrcir" },
                { "\u2949",        "Uarrocir" },
                { "\u294a",        "lurdshar" },
                { "\u294b",        "ldrushar" },
                { "\u294e",        "LeftRightVector" },
                { "\u294f",        "RightUpDownVector" },
                { "\u2950",        "DownLeftRightVector" },
                { "\u2951",        "LeftUpDownVector" },
                { "\u2952",        "LeftVectorBar" },
                { "\u2953",        "RightVectorBar" },
                { "\u2954",        "RightUpVectorBar" },
                { "\u2955",        "RightDownVectorBar" },
                { "\u2956",        "DownLeftVectorBar" },
                { "\u2957",        "DownRightVectorBar" },
                { "\u2958",        "LeftUpVectorBar" },
                { "\u2959",        "LeftDownVectorBar" },
                { "\u295a",        "LeftTeeVector" },
                { "\u295b",        "RightTeeVector" },
                { "\u295c",        "RightUpTeeVector" },
                { "\u295d",        "RightDownTeeVector" },
                { "\u295e",        "DownLeftTeeVector" },
                { "\u295f",        "DownRightTeeVector" },
                { "\u2960",        "LeftUpTeeVector" },
                { "\u2961",        "LeftDownTeeVector" },
                { "\u2962",        "lHar" },
                { "\u2963",        "uHar" },
                { "\u2964",        "rHar" },
                { "\u2965",        "dHar" },
                { "\u2966",        "luruhar" },
                { "\u2967",        "ldrdhar" },
                { "\u2968",        "ruluhar" },
                { "\u2969",        "rdldhar" },
                { "\u296a",        "lharul" },
                { "\u296b",        "llhard" },
                { "\u296c",        "rharul" },
                { "\u296d",        "lrhard" },
                { "\u296e",        "UpEquilibrium", "udhar" },
                { "\u296f",        "ReverseUpEquilibrium", "duhar" },
                { "\u2970",        "RoundImplies" },
                { "\u2971",        "erarr" },
                { "\u2972",        "simrarr" },
                { "\u2973",        "larrsim" },
                { "\u2974",        "rarrsim" },
                { "\u2975",        "rarrap" },
                { "\u2976",        "ltlarr" },
                { "\u2978",        "gtrarr" },
                { "\u2979",        "subrarr" },
                { "\u297b",        "suplarr" },
                { "\u297c",        "lfisht" },
                { "\u297d",        "rfisht" },
                { "\u297e",        "ufisht" },
                { "\u297f",        "dfisht" },
                { "\u2985",        "lopar" },
                { "\u2986",        "ropar" },
                { "\u298b",        "lbrke" },
                { "\u298c",        "rbrke" },
                { "\u298d",        "lbrkslu" },
                { "\u298e",        "rbrksld" },
                { "\u298f",        "lbrksld" },
                { "\u2990",        "rbrkslu" },
                { "\u2991",        "langd" },
                { "\u2992",        "rangd" },
                { "\u2993",        "lparlt" },
                { "\u2994",        "rpargt" },
                { "\u2995",        "gtlPar" },
                { "\u2996",        "ltrPar" },
                { "\u299a",        "vzigzag" },
                { "\u299c",        "vangrt" },
                { "\u299d",        "angrtvbd" },
                { "\u29a4",        "ange" },
                { "\u29a5",        "range" },
                { "\u29a6",        "dwangle" },
                { "\u29a7",        "uwangle" },
                { "\u29a8",        "angmsdaa" },
                { "\u29a9",        "angmsdab" },
                { "\u29aa",        "angmsdac" },
                { "\u29ab",        "angmsdad" },
                { "\u29ac",        "angmsdae" },
                { "\u29ad",        "angmsdaf" },
                { "\u29ae",        "angmsdag" },
                { "\u29af",        "angmsdah" },
                { "\u29b0",        "bemptyv" },
                { "\u29b1",        "demptyv" },
                { "\u29b2",        "cemptyv" },
                { "\u29b3",        "raemptyv" },
                { "\u29b4",        "laemptyv" },
                { "\u29b5",        "ohbar" },
                { "\u29b6",        "omid" },
                { "\u29b7",        "opar" },
                { "\u29b9",        "operp" },
                { "\u29bb",        "olcross" },
                { "\u29bc",        "odsold" },
                { "\u29be",        "olcir" },
                { "\u29bf",        "ofcir" },
                { "\u29c0",        "olt" },
                { "\u29c1",        "ogt" },
                { "\u29c2",        "cirscir" },
                { "\u29c3",        "cirE" },
                { "\u29c4",        "solb" },
                { "\u29c5",        "bsolb" },
                { "\u29c9",        "boxbox" },
                { "\u29cd",        "trisb" },
                { "\u29ce",        "rtriltri" },
                { "\u29cf",        "LeftTriangleBar" },
                { "\u29d0",        "RightTriangleBar" },
                { "\u29dc",        "iinfin" },
                { "\u29dd",        "infintie" },
                { "\u29de",        "nvinfin" },
                { "\u29e3",        "eparsl" },
                { "\u29e4",        "smeparsl" },
                { "\u29e5",        "eqvparsl" },
                { "\u29eb",        "blacklozenge", "lozf" },
                { "\u29f4",        "RuleDelayed" },
                { "\u29f6",        "dsol" },
                { "\u2a00",        "bigodot", "xodot" },
                { "\u2a01",        "bigoplus", "xoplus" },
                { "\u2a02",        "bigotimes", "xotime" },
                { "\u2a04",        "biguplus", "xuplus" },
                { "\u2a06",        "bigsqcup", "xsqcup" },
                { "\u2a0c",        "iiiint", "qint" },
                { "\u2a0d",        "fpartint" },
                { "\u2a10",        "cirfnint" },
                { "\u2a11",        "awint" },
                { "\u2a12",        "rppolint" },
                { "\u2a13",        "scpolint" },
                { "\u2a14",        "npolint" },
                { "\u2a15",        "pointint" },
                { "\u2a16",        "quatint" },
                { "\u2a17",        "intlarhk" },
                { "\u2a22",        "pluscir" },
                { "\u2a23",        "plusacir" },
                { "\u2a24",        "simplus" },
                { "\u2a25",        "plusdu" },
                { "\u2a26",        "plussim" },
                { "\u2a27",        "plustwo" },
                { "\u2a29",        "mcomma" },
                { "\u2a2a",        "minusdu" },
                { "\u2a2d",        "loplus" },
                { "\u2a2e",        "roplus" },
                { "\u2a2f",        "Cross" },
                { "\u2a30",        "timesd" },
                { "\u2a31",        "timesbar" },
                { "\u2a33",        "smashp" },
                { "\u2a34",        "lotimes" },
                { "\u2a35",        "rotimes" },
                { "\u2a36",        "otimesas" },
                { "\u2a37",        "Otimes" },
                { "\u2a38",        "odiv" },
                { "\u2a39",        "triplus" },
                { "\u2a3a",        "triminus" },
                { "\u2a3b",        "tritime" },
                { "\u2a3c",        "intprod", "iprod" },
                { "\u2a3f",        "amalg" },
                { "\u2a40",        "capdot" },
                { "\u2a42",        "ncup" },
                { "\u2a43",        "ncap" },
                { "\u2a44",        "capand" },
                { "\u2a45",        "cupor" },
                { "\u2a46",        "cupcap" },
                { "\u2a47",        "capcup" },
                { "\u2a48",        "cupbrcap" },
                { "\u2a49",        "capbrcup" },
                { "\u2a4a",        "cupcup" },
                { "\u2a4b",        "capcap" },
                { "\u2a4c",        "ccups" },
                { "\u2a4d",        "ccaps" },
                { "\u2a50",        "ccupssm" },
                { "\u2a53",        "And" },
                { "\u2a54",        "Or" },
                { "\u2a55",        "andand" },
                { "\u2a56",        "oror" },
                { "\u2a57",        "orslope" },
                { "\u2a58",        "andslope" },
                { "\u2a5a",        "andv" },
                { "\u2a5b",        "orv" },
                { "\u2a5c",        "andd" },
                { "\u2a5d",        "ord" },
                { "\u2a5f",        "wedbar" },
                { "\u2a66",        "sdote" },
                { "\u2a6a",        "simdot" },
                { "\u2a6d",        "congdot" },
                { "\u2a6e",        "easter" },
                { "\u2a6f",        "apacir" },
                { "\u2a70",        "apE" },
                { "\u2a71",        "eplus" },
                { "\u2a72",        "pluse" },
                { "\u2a73",        "Esim" },
                { "\u2a74",        "Colone" },
                { "\u2a75",        "Equal" },
                { "\u2a77",        "ddotseq", "eDDot" },
                { "\u2a78",        "equivDD" },
                { "\u2a79",        "ltcir" },
                { "\u2a7a",        "gtcir" },
                { "\u2a7b",        "ltquest" },
                { "\u2a7c",        "gtquest" },
                { "\u2a7d",        "LessSlantEqual", "leqslant", "les" },
                { "\u2a7e",        "GreaterSlantEqual", "geqslant", "ges" },
                { "\u2a7f",        "lesdot" },
                { "\u2a80",        "gesdot" },
                { "\u2a81",        "lesdoto" },
                { "\u2a82",        "gesdoto" },
                { "\u2a83",        "lesdotor" },
                { "\u2a84",        "gesdotol" },
                { "\u2a85",        "lap", "lessapprox" },
                { "\u2a86",        "gap", "gtrapprox" },
                { "\u2a87",        "lne", "lneq" },
                { "\u2a88",        "gne", "gneq" },
                { "\u2a89",        "lnap", "lnapprox" },
                { "\u2a8a",        "gnap", "gnapprox" },
                { "\u2a8b",        "lEg", "lesseqqgtr" },
                { "\u2a8c",        "gEl", "gtreqqless" },
                { "\u2a8d",        "lsime" },
                { "\u2a8e",        "gsime" },
                { "\u2a8f",        "lsimg" },
                { "\u2a90",        "gsiml" },
                { "\u2a91",        "lgE" },
                { "\u2a92",        "glE" },
                { "\u2a93",        "lesges" },
                { "\u2a94",        "gesles" },
                { "\u2a95",        "els", "eqslantless" },
                { "\u2a96",        "egs", "eqslantgtr" },
                { "\u2a97",        "elsdot" },
                { "\u2a98",        "egsdot" },
                { "\u2a99",        "el" },
                { "\u2a9a",        "eg" },
                { "\u2a9d",        "siml" },
                { "\u2a9e",        "simg" },
                { "\u2a9f",        "simlE" },
                { "\u2aa0",        "simgE" },
                { "\u2aa1",        "LessLess" },
                { "\u2aa2",        "GreaterGreater" },
                { "\u2aa4",        "glj" },
                { "\u2aa5",        "gla" },
                { "\u2aa6",        "ltcc" },
                { "\u2aa7",        "gtcc" },
                { "\u2aa8",        "lescc" },
                { "\u2aa9",        "gescc" },
                { "\u2aaa",        "smt" },
                { "\u2aab",        "lat" },
                { "\u2aac",        "smte" },
                { "\u2aad",        "late" },
                { "\u2aae",        "bumpE" },
                { "\u2aaf",        "PrecedesEqual", "pre", "preceq" },
                { "\u2ab0",        "SucceedsEqual", "sce", "succeq" },
                { "\u2ab3",        "prE" },
                { "\u2ab4",        "scE" },
                { "\u2ab5",        "precneqq", "prnE" },
                { "\u2ab6",        "scnE", "succneqq" },
                { "\u2ab7",        "prap", "precapprox" },
                { "\u2ab8",        "scap", "succapprox" },
                { "\u2ab9",        "precnapprox", "prnap" },
                { "\u2aba",        "scnap", "succnapprox" },
                { "\u2abb",        "Pr" },
                { "\u2abc",        "Sc" },
                { "\u2abd",        "subdot" },
                { "\u2abe",        "supdot" },
                { "\u2abf",        "subplus" },
                { "\u2ac0",        "supplus" },
                { "\u2ac1",        "submult" },
                { "\u2ac2",        "supmult" },
                { "\u2ac3",        "subedot" },
                { "\u2ac4",        "supedot" },
                { "\u2ac5",        "subE", "subseteqq" },
                { "\u2ac6",        "supE", "supseteqq" },
                { "\u2ac7",        "subsim" },
                { "\u2ac8",        "supsim" },
                { "\u2acb",        "subnE", "subsetneqq" },
                { "\u2acc",        "supnE", "supsetneqq" },
                { "\u2acf",        "csub" },
                { "\u2ad0",        "csup" },
                { "\u2ad1",        "csube" },
                { "\u2ad2",        "csupe" },
                { "\u2ad3",        "subsup" },
                { "\u2ad4",        "supsub" },
                { "\u2ad5",        "subsub" },
                { "\u2ad6",        "supsup" },
                { "\u2ad7",        "suphsub" },
                { "\u2ad8",        "supdsub" },
                { "\u2ad9",        "forkv" },
                { "\u2ada",        "topfork" },
                { "\u2adb",        "mlcp" },
                { "\u2ae4",        "Dashv", "DoubleLeftTee" },
                { "\u2ae6",        "Vdashl" },
                { "\u2ae7",        "Barv" },
                { "\u2ae8",        "vBar" },
                { "\u2ae9",        "vBarv" },
                { "\u2aeb",        "Vbar" },
                { "\u2aec",        "Not" },
                { "\u2aed",        "bNot" },
                { "\u2aee",        "rnmid" },
                { "\u2aef",        "cirmid" },
                { "\u2af0",        "midcir" },
                { "\u2af1",        "topcir" },
                { "\u2af2",        "nhpar" },
                { "\u2af3",        "parsim" },
                { "\u2afd",        "parsl" },
                { "\ufb00",        "fflig" },
                { "\ufb01",        "filig" },
                { "\ufb02",        "fllig" },
                { "\ufb03",        "ffilig" },
                { "\ufb04",        "ffllig" },
                { "\U0001d49c",    "Ascr" },
                { "\U0001d49e",    "Cscr" },
                { "\U0001d49f",    "Dscr" },
                { "\U0001d4a2",    "Gscr" },
                { "\U0001d4a5",    "Jscr" },
                { "\U0001d4a6",    "Kscr" },
                { "\U0001d4a9",    "Nscr" },
                { "\U0001d4aa",    "Oscr" },
                { "\U0001d4ab",    "Pscr" },
                { "\U0001d4ac",    "Qscr" },
                { "\U0001d4ae",    "Sscr" },
                { "\U0001d4af",    "Tscr" },
                { "\U0001d4b0",    "Uscr" },
                { "\U0001d4b1",    "Vscr" },
                { "\U0001d4b2",    "Wscr" },
                { "\U0001d4b3",    "Xscr" },
                { "\U0001d4b4",    "Yscr" },
                { "\U0001d4b5",    "Zscr" },
                { "\U0001d4b6",    "ascr" },
                { "\U0001d4b7",    "bscr" },
                { "\U0001d4b8",    "cscr" },
                { "\U0001d4b9",    "dscr" },
                { "\U0001d4bb",    "fscr" },
                { "\U0001d4bd",    "hscr" },
                { "\U0001d4be",    "iscr" },
                { "\U0001d4bf",    "jscr" },
                { "\U0001d4c0",    "kscr" },
                { "\U0001d4c1",    "lscr" },
                { "\U0001d4c2",    "mscr" },
                { "\U0001d4c3",    "nscr" },
                { "\U0001d4c5",    "pscr" },
                { "\U0001d4c6",    "qscr" },
                { "\U0001d4c7",    "rscr" },
                { "\U0001d4c8",    "sscr" },
                { "\U0001d4c9",    "tscr" },
                { "\U0001d4ca",    "uscr" },
                { "\U0001d4cb",    "vscr" },
                { "\U0001d4cc",    "wscr" },
                { "\U0001d4cd",    "xscr" },
                { "\U0001d4ce",    "yscr" },
                { "\U0001d4cf",    "zscr" },
                { "\U0001d504",    "Afr" },
                { "\U0001d505",    "Bfr" },
                { "\U0001d507",    "Dfr" },
                { "\U0001d508",    "Efr" },
                { "\U0001d509",    "Ffr" },
                { "\U0001d50a",    "Gfr" },
                { "\U0001d50d",    "Jfr" },
                { "\U0001d50e",    "Kfr" },
                { "\U0001d50f",    "Lfr" },
                { "\U0001d510",    "Mfr" },
                { "\U0001d511",    "Nfr" },
                { "\U0001d512",    "Ofr" },
                { "\U0001d513",    "Pfr" },
                { "\U0001d514",    "Qfr" },
                { "\U0001d516",    "Sfr" },
                { "\U0001d517",    "Tfr" },
                { "\U0001d518",    "Ufr" },
                { "\U0001d519",    "Vfr" },
                { "\U0001d51a",    "Wfr" },
                { "\U0001d51b",    "Xfr" },
                { "\U0001d51c",    "Yfr" },
                { "\U0001d51e",    "afr" },
                { "\U0001d51f",    "bfr" },
                { "\U0001d520",    "cfr" },
                { "\U0001d521",    "dfr" },
                { "\U0001d522",    "efr" },
                { "\U0001d523",    "ffr" },
                { "\U0001d524",    "gfr" },
                { "\U0001d525",    "hfr" },
                { "\U0001d526",    "ifr" },
                { "\U0001d527",    "jfr" },
                { "\U0001d528",    "kfr" },
                { "\U0001d529",    "lfr" },
                { "\U0001d52a",    "mfr" },
                { "\U0001d52b",    "nfr" },
                { "\U0001d52c",    "ofr" },
                { "\U0001d52d",    "pfr" },
                { "\U0001d52e",    "qfr" },
                { "\U0001d52f",    "rfr" },
                { "\U0001d530",    "sfr" },
                { "\U0001d531",    "tfr" },
                { "\U0001d532",    "ufr" },
                { "\U0001d533",    "vfr" },
                { "\U0001d534",    "wfr" },
                { "\U0001d535",    "xfr" },
                { "\U0001d536",    "yfr" },
                { "\U0001d537",    "zfr" },
                { "\U0001d538",    "Aopf" },
                { "\U0001d539",    "Bopf" },
                { "\U0001d53b",    "Dopf" },
                { "\U0001d53c",    "Eopf" },
                { "\U0001d53d",    "Fopf" },
                { "\U0001d53e",    "Gopf" },
                { "\U0001d540",    "Iopf" },
                { "\U0001d541",    "Jopf" },
                { "\U0001d542",    "Kopf" },
                { "\U0001d543",    "Lopf" },
                { "\U0001d544",    "Mopf" },
                { "\U0001d546",    "Oopf" },
                { "\U0001d54a",    "Sopf" },
                { "\U0001d54b",    "Topf" },
                { "\U0001d54c",    "Uopf" },
                { "\U0001d54d",    "Vopf" },
                { "\U0001d54e",    "Wopf" },
                { "\U0001d54f",    "Xopf" },
                { "\U0001d550",    "Yopf" },
                { "\U0001d552",    "aopf" },
                { "\U0001d553",    "bopf" },
                { "\U0001d554",    "copf" },
                { "\U0001d555",    "dopf" },
                { "\U0001d556",    "eopf" },
                { "\U0001d557",    "fopf" },
                { "\U0001d558",    "gopf" },
                { "\U0001d559",    "hopf" },
                { "\U0001d55a",    "iopf" },
                { "\U0001d55b",    "jopf" },
                { "\U0001d55c",    "kopf" },
                { "\U0001d55d",    "lopf" },
                { "\U0001d55e",    "mopf" },
                { "\U0001d55f",    "nopf" },
                { "\U0001d560",    "oopf" },
                { "\U0001d561",    "popf" },
                { "\U0001d562",    "qopf" },
                { "\U0001d563",    "ropf" },
                { "\U0001d564",    "sopf" },
                { "\U0001d565",    "topf" },
                { "\U0001d566",    "uopf" },
                { "\U0001d567",    "vopf" },
                { "\U0001d568",    "wopf" },
                { "\U0001d569",    "xopf" },
                { "\U0001d56a",    "yopf" },
                { "\U0001d56b",    "zopf" },
                { "\u003c\u20d2",  "nvlt" },
                { "\u003d\u20e5",  "bne" },
                { "\u003e\u20d2",  "nvgt" },
                { "\u0066\u006a",  "fjlig" },
                { "\u205f\u200a",  "ThickSpace" },
                { "\u219d\u0338",  "nrarrw" },
                { "\u2202\u0338",  "npart" },
                { "\u2220\u20d2",  "nang" },
                { "\u2229\ufe00",  "caps" },
                { "\u222a\ufe00",  "cups" },
                { "\u223c\u20d2",  "nvsim" },
                { "\u223d\u0331",  "race" },
                { "\u223e\u0333",  "acE" },
                { "\u2242\u0338",  "NotEqualTilde", "nesim" },
                { "\u224b\u0338",  "napid" },
                { "\u224d\u20d2",  "nvap" },
                { "\u224e\u0338",  "NotHumpDownHump", "nbump" },
                { "\u224f\u0338",  "NotHumpEqual", "nbumpe" },
                { "\u2250\u0338",  "nedot" },
                { "\u2261\u20e5",  "bnequiv" },
                { "\u2264\u20d2",  "nvle" },
                { "\u2265\u20d2",  "nvge" },
                { "\u2266\u0338",  "nlE", "nleqq" },
                { "\u2267\u0338",  "NotGreaterFullEqual", "ngE", "ngeqq" },
                { "\u2268\ufe00",  "lvertneqq", "lvnE" },
                { "\u2269\ufe00",  "gvertneqq", "gvnE" },
                { "\u226a\u0338",  "NotLessLess", "nLtv" },
                { "\u226a\u20d2",  "nLt" },
                { "\u226b\u0338",  "NotGreaterGreater", "nGtv" },
                { "\u226b\u20d2",  "nGt" },
                { "\u227f\u0338",  "NotSucceedsTilde" },
                { "\u2282\u20d2",  "NotSubset", "nsubset", "vnsub" },
                { "\u2283\u20d2",  "NotSuperset", "nsupset", "vnsup" },
                { "\u228a\ufe00",  "varsubsetneq", "vsubne" },
                { "\u228b\ufe00",  "varsupsetneq", "vsupne" },
                { "\u228f\u0338",  "NotSquareSubset" },
                { "\u2290\u0338",  "NotSquareSuperset" },
                { "\u2293\ufe00",  "sqcaps" },
                { "\u2294\ufe00",  "sqcups" },
                { "\u22b4\u20d2",  "nvltrie" },
                { "\u22b5\u20d2",  "nvrtrie" },
                { "\u22d8\u0338",  "nLl" },
                { "\u22d9\u0338",  "nGg" },
                { "\u22da\ufe00",  "lesg" },
                { "\u22db\ufe00",  "gesl" },
                { "\u22f5\u0338",  "notindot" },
                { "\u22f9\u0338",  "notinE" },
                { "\u2933\u0338",  "nrarrc" },
                { "\u29cf\u0338",  "NotLeftTriangleBar" },
                { "\u29d0\u0338",  "NotRightTriangleBar" },
                { "\u2a6d\u0338",  "ncongdot" },
                { "\u2a70\u0338",  "napE" },
                { "\u2a7d\u0338",  "NotLessSlantEqual", "nleqslant", "nles" },
                { "\u2a7e\u0338",  "NotGreaterSlantEqual", "ngeqslant", "nges" },
                { "\u2aa1\u0338",  "NotNestedLessLess" },
                { "\u2aa2\u0338",  "NotNestedGreaterGreater" },
                { "\u2aac\ufe00",  "smtes" },
                { "\u2aad\ufe00",  "lates" },
                { "\u2aaf\u0338",  "NotPrecedesEqual", "npre", "npreceq" },
                { "\u2ab0\u0338",  "NotSucceedsEqual", "nsce", "nsucceq" },
                { "\u2ac5\u0338",  "nsubE", "nsubseteqq" },
                { "\u2ac6\u0338",  "nsupE", "nsupseteqq" },
                { "\u2acb\ufe00",  "varsubsetneqq", "vsubnE" },
                { "\u2acc\ufe00",  "varsupsetneqq", "vsupnE" },
                { "\u2afd\u20e5",  "nparsl" },

            };

            StringViewMap map;

            for (auto& row: inverse_map)
                for (auto& name: irange(row.begin() + 1, row.end()))
                    map.insert({name, row[0]});

            return map;

        }();

        return map;

    }

}
