// This file is generated by the rs-bump-version script

#pragma once

#include <string>
#include <array>

namespace Crow {

    inline std::array<int, 3> version() noexcept {
        return {{ 2, 0, 69 }};
    }

    inline std::string version_string() {
        return "2.0.69";
    }

}
